### ISSUE TITLE
Server crash on loading

### ISSUE THREAD

**Issue by bloodyraoul** [refinedmods/refinedstorage#2579]
#### Issue description:

Server crash on loading with log :
[Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: com/raoulvdberge/refinedstorage/api/storage/disk/IStorageDiskProvider

#### Version (make sure you are on the latest version before reporting):

- Minecraft: 1.15.2
- Forge: 31.2.20
- Refined Storage: 1.8.5

**Comment by Darkere** [comment]
I'm guessing this is caused by ExtraDisks. But I don't know for sure without a crash report. 

All add-ons need to be updated to work with 1.8.5.

**Comment by bloodyraoul** [comment]
you're right
thank you
